title: Lutao Yan
description: Personal academic website of Lutao Yan, focusing on multimodal learning, chart understanding, visual analytics, and information retrieval.
#Comment out url when working locally to resolve base urls correctly
url: https://yanlutao-scut.github.io

# Owner/author information
owner:
  name: Lutao Yan
  avatar: lutao-profile.jpg
  bio: MPhil student at HKUST(GZ), working on multimodal chart understanding and information retrieval.
  email: lutaoyan@foxmail.com
  cv: /file/ylt_resume.pdf
  # Social networking links used in the author sidebar.
  github: yanlutao-scut
  scholar: https://scholar.google.com/citations?user=QmD2qrYAAAAJ&hl=zh-CN

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Experience
    url: /experience/
  - title: Awards
    url: /awards/
  - title: CV
    url: /file/ylt_resume.pdf

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


include: [".htaccess"]
exclude:
  - backup
  - blogs
  - md
  - .idea
  - blogs.md
  - file/404.md
  - file/SoP.md
  - file/awards-zh.md
  - file/publications-zh.md
  - honor.md
  - moment.md
  - project.md
  - teams.md
  - lib
  - config.rb
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - less
  - minimal-mistakes.sublime-project
  - minimal-mistakes.sublime-workspace
